 DROP TABLE "NEOIB_SI"."IMSI_USR_DAT";

CREATE SEQUENCE IMSI_USR_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 999999
       NOCYCLE
       NOCACHE
       NOORDER;
     
 CREATE TABLE "NEOIB_SI"."IMSI_USR_DAT" (	
 	"IDX" NUMBER(10,0) NOT NULL ENABLE, 
	"USR_ID" VARCHAR2(50), 
	"USR_NM" VARCHAR2(50), 
	"CNTRY" VARCHAR2(50), 
	"PHONE" VARCHAR2(50), 
	"COLOR" VARCHAR2(50), 
	"PRICE" NUMBER(11,2),
	"QUAN" NUMBER(11),
	"DT" DATE, 
	"CDT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UDT" DATE, 
	 CONSTRAINT "IMSI_USR_DAT_PK" PRIMARY KEY ("IDX")
);

SELECT 	  ROWNUM AS IDX
		, USR_ID
		, USR_NM
		, CNTRY
		, PHONE
		, COLOR
		, PRICE
		, QUAN
		, TO_CHAR(DT, 'YYYY-MM-DD') AS DT
FROM IMSI_USR_DAT
ORDER BY DT;

insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0001','Steve','USA','IPad Air','Green',630700,3,TO_DATE('2014-10-01', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0002','Emma','Korea','LG G3','Pink',503800,1,TO_DATE('2014-09-30', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0003','Emma','Japan','IPad Air','Yellow',66900,7,TO_DATE('2014-09-29', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0004','Emma','UK','Galaxy Note3','Orange',458300,9,TO_DATE('2014-09-28', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0005','Anna','China','LG G3','Violet',168100,10,TO_DATE('2014-09-27', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0006','Anna','USA','Galaxy S5','Gray',10400,3,TO_DATE('2014-09-26', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0007','Lowrence','Ireland','LG G3','Yellow',696100,12,TO_DATE('2014-09-25', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0008','Lowrence','Ireland','Galaxy Note3','Yellow',623600,12,TO_DATE('2014-09-24', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0009','Kim','Japan','IPad Air','Gray',8000,7,TO_DATE('2014-09-23', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0010','Kim','UK','Galaxy S5','Orange',982600,9,TO_DATE('2014-09-22', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0011','Jennifer','UK','IPad Air','Green',800400,9,TO_DATE('2014-09-21', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0012','Steve','Japan','Galaxy Note3','Yellow',740100,7,TO_DATE('2014-09-20', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0013','Emma','Singapore','IPhone 5S','Green',868400,20,TO_DATE('2014-09-19', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0014','Anna','Italy','Galaxy S5','Violet',266800,15,TO_DATE('2014-09-18', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0015','Steve','China','IPad Air','Pink',848100,10,TO_DATE('2014-09-17', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0016','Emma','Italy','IPad Air','Pink',401900,15,TO_DATE('2014-09-16', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0017','Anna','Singapore','IPad Air','Green',969700,20,TO_DATE('2014-09-15', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0018','Steve','Japan','LG G3','Orange',204700,7,TO_DATE('2014-09-14', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0019','Steve','Korea','LG G3','Orange',808000,1,TO_DATE('2014-09-13', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0020','Anna','Japan','Galaxy S5','Gray',701800,7,TO_DATE('2014-09-12', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0021','Kim','UK','IPad Air','Pink',31000,9,TO_DATE('2014-09-11', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0022','Kim','China','LG G3','Blue',640200,10,TO_DATE('2014-09-10', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0023','Anna','Singapore','IPad Air','Green',149300,20,TO_DATE('2014-09-09', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0024','Emma','France','IPhone 5S','Violet',234800,0,TO_DATE('2014-09-08', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0025','Kim','USA','IPad Air','Gray',269000,3,TO_DATE('2014-09-07', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0026','Emma','Korea','IPhone 5S','Blue',917700,1,TO_DATE('2014-09-06', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0027','Jennifer','China','Galaxy S5','Yellow',838900,10,TO_DATE('2014-09-05', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0028','Jennifer','Singapore','Galaxy S5','Violet',93700,20,TO_DATE('2014-09-04', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0029','Kim','France','IPad Air','Blue',403500,0,TO_DATE('2014-09-03', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0030','Steve','UK','Galaxy Note3','Yellow',881000,9,TO_DATE('2014-09-02', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0031','Lowrence','Singapore','Galaxy S5','Pink',348000,20,TO_DATE('2014-09-01', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0032','Steve','Japan','IPad Air','Gray',871700,7,TO_DATE('2014-08-31', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0033','Anna','UK','IPhone 5S','Yellow',653100,9,TO_DATE('2014-08-30', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0034','Kim','Korea','IPhone 5S','Gray',873500,1,TO_DATE('2014-08-29', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0035','Steve','UK','IPad Air','Orange',643600,9,TO_DATE('2014-08-28', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0036','Emma','Italy','IPhone 5S','Orange',664200,15,TO_DATE('2014-08-27', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0037','Lowrence','China','IPhone 5S','Orange',736900,10,TO_DATE('2014-08-26', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0038','Kim','Italy','Galaxy S5','Gray',739300,15,TO_DATE('2014-08-25', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0039','Lowrence','Ireland','LG G3','Pink',195600,12,TO_DATE('2014-08-24', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0040','Lowrence','Singapore','IPhone 5S','Pink',64500,20,TO_DATE('2014-08-23', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0041','Lowrence','Singapore','IPhone 5S','Blue',873400,20,TO_DATE('2014-08-22', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0042','Steve','USA','IPhone 5S','Orange',821600,3,TO_DATE('2014-08-21', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0043','Kim','UK','Galaxy S5','Yellow',971100,9,TO_DATE('2014-08-20', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0044','Kim','China','Galaxy Note3','Blue',165400,10,TO_DATE('2014-08-19', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0045','Jennifer','Italy','IPhone 5S','Yellow',781600,15,TO_DATE('2014-08-18', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0046','Kim','Italy','Galaxy Note3','Orange',964400,15,TO_DATE('2014-08-17', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0047','Jennifer','USA','LG G3','Violet',441200,3,TO_DATE('2014-08-16', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0048','Kim','Singapore','LG G3','Yellow',560900,20,TO_DATE('2014-08-15', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0049','Lowrence','France','Galaxy S5','Gray',680000,0,TO_DATE('2014-08-14', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0050','Steve','UK','Galaxy S5','Violet',512100,9,TO_DATE('2014-08-13', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0051','Jennifer','Korea','IPad Air','Yellow',572800,1,TO_DATE('2014-08-12', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0052','Steve','USA','Galaxy Note3','Green',345600,3,TO_DATE('2014-08-11', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0053','Emma','Ireland','LG G3','Violet',287600,12,TO_DATE('2014-08-10', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0054','Steve','Ireland','IPad Air','Pink',307500,12,TO_DATE('2014-08-09', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0055','Emma','Korea','IPhone 5S','Yellow',835200,1,TO_DATE('2014-08-08', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0056','Lowrence','Singapore','IPad Air','Pink',112800,20,TO_DATE('2014-08-07', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0057','Anna','Japan','IPad Air','Orange',822200,7,TO_DATE('2014-08-06', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0058','Lowrence','Singapore','Galaxy S5','Violet',694300,20,TO_DATE('2014-08-05', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0059','Jennifer','France','LG G3','Green',197900,0,TO_DATE('2014-08-04', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0060','Steve','Japan','IPhone 5S','Blue',955200,7,TO_DATE('2014-08-03', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0061','Kim','Korea','Galaxy Note3','Yellow',4400,1,TO_DATE('2014-08-02', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0062','Emma','UK','Galaxy S5','Green',517100,9,TO_DATE('2014-08-01', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0063','Emma','France','Galaxy S5','Violet',128500,0,TO_DATE('2014-07-31', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0064','Lowrence','Ireland','Galaxy Note3','Pink',468700,12,TO_DATE('2014-07-30', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0065','Lowrence','Singapore','IPhone 5S','Green',51100,20,TO_DATE('2014-07-29', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0066','Emma','Singapore','LG G3','Gray',119300,20,TO_DATE('2014-07-28', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0067','Lowrence','China','LG G3','Yellow',595800,10,TO_DATE('2014-07-27', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0068','Anna','Ireland','IPad Air','Yellow',745200,12,TO_DATE('2014-07-26', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0069','Lowrence','Singapore','LG G3','Gray',681300,20,TO_DATE('2014-07-25', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0070','Anna','USA','Galaxy S5','Orange',344100,3,TO_DATE('2014-07-24', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0071','Lowrence','UK','Galaxy S5','Blue',69700,9,TO_DATE('2014-07-23', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0072','Kim','France','Galaxy S5','Violet',379700,0,TO_DATE('2014-07-22', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0073','Jennifer','Italy','Galaxy S5','Pink',115300,15,TO_DATE('2014-07-21', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0074','Jennifer','Korea','LG G3','Yellow',535700,1,TO_DATE('2014-07-20', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0075','Jennifer','China','IPad Air','Green',517500,10,TO_DATE('2014-07-19', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0076','Lowrence','China','IPad Air','Pink',464900,10,TO_DATE('2014-07-18', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0077','Jennifer','Singapore','Galaxy S5','Gray',70300,20,TO_DATE('2014-07-17', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0078','Lowrence','France','LG G3','Pink',538000,0,TO_DATE('2014-07-16', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0079','Emma','USA','Galaxy Note3','Violet',409000,3,TO_DATE('2014-07-15', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0080','Emma','Italy','LG G3','Pink',595000,15,TO_DATE('2014-07-14', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0081','Kim','Singapore','IPad Air','Blue',764800,20,TO_DATE('2014-07-13', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0082','Kim','Ireland','Galaxy Note3','Orange',694500,12,TO_DATE('2014-07-12', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0083','Kim','China','Galaxy Note3','Green',712300,10,TO_DATE('2014-07-11', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0084','Anna','Ireland','IPhone 5S','Blue',863700,12,TO_DATE('2014-07-10', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0085','Emma','Ireland','LG G3','Violet',918900,12,TO_DATE('2014-07-09', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0086','Jennifer','Japan','Galaxy Note3','Pink',849000,7,TO_DATE('2014-07-08', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0087','Anna','Italy','Galaxy S5','Green',896600,15,TO_DATE('2014-07-07', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0088','Anna','Korea','IPad Air','Yellow',865100,1,TO_DATE('2014-07-06', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0089','Emma','Ireland','Galaxy Note3','Orange',750900,12,TO_DATE('2014-07-05', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0090','Lowrence','France','IPad Air','Violet',345900,0,TO_DATE('2014-07-04', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0091','Emma','Korea','Galaxy Note3','Pink',930700,1,TO_DATE('2014-07-03', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0092','Kim','Singapore','LG G3','Violet',692700,20,TO_DATE('2014-07-02', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0093','Kim','Ireland','IPhone 5S','Violet',979100,12,TO_DATE('2014-07-01', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0094','Kim','Korea','LG G3','Gray',28200,1,TO_DATE('2014-06-30', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0095','Jennifer','Italy','Galaxy Note3','Pink',283700,15,TO_DATE('2014-06-29', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0096','Anna','Japan','Galaxy Note3','Pink',940000,7,TO_DATE('2014-06-28', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0097','Kim','Italy','IPad Air','Pink',822900,15,TO_DATE('2014-06-27', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0098','Lowrence','France','Galaxy Note3','Pink',239400,0,TO_DATE('2014-06-26', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0099','Lowrence','Korea','Galaxy Note3','Gray',922600,1,TO_DATE('2014-06-25', 'YYYY-MM-DD')	);
insert into IMSI_USR_DAT(IDX,USR_ID,USR_NM,CNTRY,PHONE,COLOR,PRICE,QUAN,DT) VALUES ( IMSI_USR_SEQ.NEXTVAL, 	'USR0100','Steve','USA','Galaxy Note3','Violet',701300,3,TO_DATE('2014-06-24', 'YYYY-MM-DD')	);




COMMIT;





